from __future__ import annotations

import uuid as uuid_lib
from typing import Dict, List

from fastapi import FastAPI, HTTPException
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field

app = FastAPI(title="logging-service", version="1.0.0")

STORE: Dict[str, str] = {}


class LogIn(BaseModel):
    id: str = Field(..., description="UUID generated by facade-service")
    msg: str = Field(..., description="Message text")


class LogOut(BaseModel):
    id: str
    stored: bool
    msg: str


@app.get("/health", tags=["system"])
def health():
    return {"status": "ok", "count": len(STORE)}


@app.post("/log", response_model=LogOut, tags=["logs"])
def add_log(payload: LogIn):
    try:
        uuid_lib.UUID(payload.id)
    except Exception as e:
        raise HTTPException(status_code=400, detail="Invalid UUID in field 'id'") from e

    if payload.id in STORE:
        print(f"[DEDUP] duplicate id={payload.id} msg='{payload.msg}'")
        return LogOut(id=payload.id, stored=False, msg=STORE[payload.id])

    STORE[payload.id] = payload.msg
    print(f"[STORE] id={payload.id} msg='{payload.msg}'")
    return LogOut(id=payload.id, stored=True, msg=payload.msg)


@app.get("/logs", tags=["logs"], response_class=PlainTextResponse)
def get_logs(format: str = "text"):
    msgs: List[str] = list(STORE.values())
    if format == "json":
        return {"messages": msgs}
    return ", ".join(msgs)
